# Generated by Django 5.2 on 2025-04-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donodopato',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='photos_perfil/'),
        ),
    ]
