# Generated by Django 5.1.6 on 2025-02-21 16:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
