# Generated by Django 5.1.6 on 2025-02-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('descricao', models.TextField(max_length=200)),
                ('data_atividade', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
