# Generated by Django 5.1.7 on 2025-03-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idadeUser',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useradmsite',
            name='idade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
