# Generated by Django 5.2 on 2025-04-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_projeto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idade',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
