# Generated by Django 5.2 on 2025-04-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_projeto', '0002_alter_usuario_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='animas',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
