# Generated by Django 5.2 on 2025-04-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_projeto', '0003_alter_usuario_animas_alter_usuario_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='biografia',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='escolaridade',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
