# Generated by Django 5.1.7 on 2025-03-14 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meu_evento', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eventos',
            new_name='Evento',
        ),
    ]
